spring:
  data:
    mongodb:
      authentication-database: admin
      username: ${MONGO_USERNAME}
      password: ${MONGO_PASSWORD}
      database: ${MONGO_DATABASE}
      port: ${MONGO_PORT}
      host: ${MONGO_HOST}
#      username: mothi
#      password: root
#      database: noteDb
#      port: 27017
#      host: localhost
  application:
    name: note-service
server:
  port: 8082
